language: node_js
node_js:
  - 12

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run
before_script:
  - docker --version # Print the version
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker build -t udagram-api-user ./udagram-api-user
  - docker build -t udagram-frontend ./udagram-frontend
  - docker build -t reverseproxy ./udagram-reverseproxy
  - docker tag udagram-api-feed huongtk35/udagram-api-feed:v2
  - docker tag udagram-api-user huongtk35/udagram-api-user:v2
  - docker tag udagram-frontend huongtk35/udagram-frontend:v2
  - docker tag reverseproxy huongtk35/reverseproxy:v2

after_success:
  - docker login -u huongtk35 -p kobaogio1
  - docker push huongtk35/udagram-api-feed:v2
  - docker push huongtk35/udagram-api-user:v2
  - docker push huongtk35/udagram-frontend:v2
  - docker push huongtk35/reverseproxy:v2
