version: 2.1

jobs:
  build:
    docker:
      - image: circleci/buildpack:stretch
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Docker Build
          command: |
            docker build -t udagram-api-feed ./udagram-api-feed
            docker build -t udagram-api-user ./udagram-api-user
            docker build -t udagram-frontend ./udagram-frontend
            docker build -t reverseproxy ./udagram-reverseproxy
            docker tag udagram-api-feed huongtk35/udagram-api-feed:v1
            docker tag udagram-api-user huongtk35/udagram-api-user:v1
            docker tag udagram-frontend huongtk35/udagram-frontend:v1
            docker tag reverseproxy huongtk35/reverseproxy:v1
            
      - run:
          name: Docker Push
          command: |
              echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
              docker push huongtk35/udagram-api-feed:v1
              docker push huongtk35/udagram-api-user:v1
              docker push huongtk35/udagram-frontend:v1
              docker push huongtk35/reverseproxy:v1